### ISSUE TITLE
services list

### ISSUE THREAD

**Issue by jelizarovas** [jelizarovas/HairByMargo.Com#12]
please list the services and prices. two questions:

do you want to display prices?
are the two categories ( male/female) or are the more?

**Comment by salonmargo** [comment]
-Just Them Hairs-
Beard Shape Up 10
Clarify & Repair 25+
Kids Cut 20
First Responder's Haircut 20
Men's Haircut 25
Women's Haircut 25
Wash & Style 25+
Haircut & Style 35+
Flat Iron or Curls 15+

Color 
Glaze 20
Root 40
All Over Color 60
Partial Highlight 75+
Full Highlight 120+
Color Camo for Men 25+
Color Correction - Consultation
Keratin Smoothing Treatment 75+
Extensions - Consultation
Additional Color Charge for Length 20
 (may or may not add depending on your professional opinion.. longer hair requires more color

**Comment by salonmargo** [comment]
If you think I shouldn’t display priced then don’t
