### ISSUE TITLE
About Salon Margo

### ISSUE THREAD

**Issue by salonmargo** [jelizarovas/HairByMargo.Com#2]

**Comment by jelizarovas** [comment]
Please in the comments provide what do you want the description to be. Thank you.

**Comment by salonmargo** [comment]
As the owner of Salon Margo, Marguerite Swan has carried out a vision far surpassing the expectations of a hair salon. Swan has worked diligently to recreate the hair salon as a place for community, familiarity, and a place to celebrate the local citizens that give back the most: first responders. Through Salon Margo, Swan has created a place that encourages first responders of the local community to have a place they can count on, develop relationships, and be in a space that affirms their bravery, courage, and civic duty. Additionally, Swan has uplifted child welfare non-profits, raised money for charity on a multitude of issues through the apparatus of her business, and has advocated at the state capital for child welfare reform. Swan has taken her passions of life and brought them into a space of positivity, encouragement, and community.

**Comment by salonmargo** [comment]
make the text a little bigger

**Comment by salonmargo** [comment]
![image](https://user-images.githubusercontent.com/60369612/73224285-facd0100-4136-11ea-94e7-21b557a9469a.png)

I saw this, and I would like something like this on the website

**Comment by jelizarovas** [comment]
Fixed. `HEAD detached at 8c4168b`, reattached to master branch.

![image](https://user-images.githubusercontent.com/15138718/73225408-715f0400-4121-11ea-9bdb-cc22839f959d.png)
