### ISSUE TITLE
Rent-a-chair change picture

### ISSUE THREAD

**Issue by jelizarovas** [jelizarovas/HairByMargo.Com#25]
![Screensho](https://user-images.githubusercontent.com/15138718/73494093-c8a2e580-4368-11ea-8844-ecf9992fead6.jpg)

That photo has to come down lol! I will send pics soon 

By Margo

**Comment by salonmargo** [comment]
ill take pics of salon tomorrow and send you them

**Comment by jelizarovas** [comment]
> ill take pics of salon tomorrow and send you them
> […](#)
> On Jan 30, 2020, at 5:00 PM, Arnas ***@***.***> wrote: ﻿ That photo has to come down lol! I will send pics soon By Margo — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

do you have new photos yet? fb post said you'll be open today

**Comment by salonmargo** [comment]
Yo, I’m on drugs rn. I just had surgery. In a lot of pain. I go to shop to,or row I’ll get the pics. I’m a tad loopy for now

**Comment by jelizarovas** [comment]
take care and relax, don't rush to answer - i'm just doing rounds right now.

Only do it when you are ready to.

Get well :)

**Comment by jelizarovas** [comment]
Margo has texted me these pictures, which one you want featured at the bottom?

![-130104519971957452](https://user-images.githubusercontent.com/15138718/74095717-7caf1980-4aa9-11ea-9dca-00f4e3ba8be1.jpg)
![-21883493242981843](https://user-images.githubusercontent.com/15138718/74095718-7d47b000-4aa9-11ea-8026-2deb3fc85325.jpg)
![-4903200511220950007](https://user-images.githubusercontent.com/15138718/74095719-7d47b000-4aa9-11ea-923d-67c219661323.jpg)
![-5363696345896036783](https://user-images.githubusercontent.com/15138718/74095720-7d47b000-4aa9-11ea-85ab-ca1e346ca020.jpg)
![-8454170224605008347](https://user-images.githubusercontent.com/15138718/74095721-7de04680-4aa9-11ea-8912-f070448f32e3.jpg)
![-8514133310335850974](https://user-images.githubusercontent.com/15138718/74095722-7de04680-4aa9-11ea-9630-e7c56cee8ca9.jpg)
![5490186684071837528](https://user-images.githubusercontent.com/15138718/74095724-7e78dd00-4aa9-11ea-90d4-9fc6262e2ec5.jpg)

**Comment by jelizarovas** [comment]
![Screenshot_20200209-104317](https://user-images.githubusercontent.com/15138718/74107843-ff2aee00-4b28-11ea-8e70-647ddb25e4ab.png)
