### ISSUE TITLE
Images needs home

### ISSUE THREAD

**Issue by jelizarovas** [jelizarovas/HairByMargo.Com#26]
![16750E76-](https://user-images.githubusercontent.com/15138718/73494198-f38d3980-4368-11ea-9ddf-9d7b77fdc363.jpg)
![3A1F7C8D-](https://user-images.githubusercontent.com/15138718/73494199-f38d3980-4368-11ea-89e4-800ffaed7109.jpg)
![IMG_3858](https://user-images.githubusercontent.com/15138718/73494200-f425d000-4368-11ea-8e88-07be7bc5828f.JPG)
![IMG_7223](https://user-images.githubusercontent.com/15138718/73494202-f425d000-4368-11ea-94ba-9cd0d8759cfc.jpg)

These images require home, where would you like them placed?

**Comment by salonmargo** [comment]
The American flag can go in gallery, the unicorn I’m trying to photoshop and the picture of me can go in the about salon Margo.. you can crop it a bit to fit

**Comment by salonmargo** [comment]
Can we link these articles? Or Is that weird?

**Comment by jelizarovas** [comment]
are you trying to photoshop yourself the logo?? what stage are you at right now?

which articles?
