### ISSUE TITLE
add website to social media/search engines

### ISSUE THREAD

**Issue by jelizarovas** [jelizarovas/HairByMargo.Com#29]
- [ ] google (pending)

- [ ]  facebook

- [x] twitter if you have any

- [x] yelp (if)

- [ ] instagram

**Comment by jelizarovas** [comment]
- [ ] create yelp account, right now it shows up on search, but links to different business

**Comment by salonmargo** [comment]
I don’t have Twitter, but I’ll create a yelp

**Comment by jelizarovas** [comment]
I think you can go to google my business and approve the website. Even after couple of days it still says it's oending

**Comment by jelizarovas** [comment]
![image](https://user-images.githubusercontent.com/15138718/73788775-81df3200-4752-11ea-8f99-99fb850b0359.png)

**Comment by jelizarovas** [comment]
![image](https://user-images.githubusercontent.com/15138718/73789099-ff0aa700-4752-11ea-8382-a490ae5f061a.png)

**Comment by jelizarovas** [comment]
I've done my part you just need to approve the changes
