### ISSUE TITLE
services

### ISSUE THREAD

**Issue by salonmargo** [jelizarovas/HairByMargo.Com#3]
hi I would like the services to be updated. they currently look like this:
![image](https://user-images.githubusercontent.com/60369612/73223744-1df6b100-4135-11ea-96de-5022e15c2806.png)
so I want new services for female hair:

no nazzi cuts
quick dye $50
...

**Comment by salonmargo** [comment]
![image](https://user-images.githubusercontent.com/60369612/73224048-416e2b80-4136-11ea-9783-ddc467621350.png)

**Comment by jelizarovas** [comment]
please have the services list ready
