### ISSUE TITLE
gallery picture change

### ISSUE THREAD

**Issue by salonmargo** [jelizarovas/HairByMargo.Com#4]
please replace this image 

![image](https://user-images.githubusercontent.com/60369612/73223819-63b37980-4135-11ea-9b49-8950949f8ec0.png)

to this image

![image](https://user-images.githubusercontent.com/60369612/73223850-7c239400-4135-11ea-9117-a5505ff7ba57.png)

**Comment by jelizarovas** [comment]
this was a test suggestion. please reopen the issue if there are any actual images you want replacing
