### ISSUE TITLE
update request

### ISSUE THREAD

**Issue by jelizarovas** [jelizarovas/HairByMargo.Com#47]
[Margo's salon website copy.docx](https://github.com/jelizarovas/HairByMargo.Com/files/5394826/Margo.s.salon.website.copy.docx)

Mission - The purpose of Salon Margo is to provide an inviting atmosphere where guests receive personalized hair services at an affordable cost with the intent of elevating self-confidence while sparking the notion of daring you to believe in yourself... One head at a time 
Achievements-
Marguerite Swan, owner and licensed cosmetologist for over 10 years, opened Salon Margo October 20th, 2017. Her passion for hair styling and cosmetology began when she gained first-hand experience building a children’s salon as product designer and manager when she was just 14 years old. After high school, she graduated Paul Mitchell the School and went on to hold an associate degree in Business Administration. At 20 years old, she worked under a platform artist where she became certified in keratin education and in 2015, earned a credit on IMDB for key hairstylist. Most recently, Salon Margo was nominated as “Hartford’s Finest 2019” for raising $1,585 for the Cystic Fibrosis Foundation. 
Goals and aspirations-
Marguerite Swan is an entrepreneur and community activist who built her own creative space working diligently and with intent. She sees every appointment as an opportunity to facilitate the betterment of the youth in her community while celebrating those who work as caregivers by helping them love what they see in the mirror. She has created a space that is more than a salon; her goal is to provide a place that boosts each client’s self-confidence while affording everyone a comfortable place to meet, talk and strengthen connections.
About Salon Margo
Having been raised in a broken foster care system her entire childhood, and while some might think this was an obstacle, she has a message for those people and for every foster child; Foster care is an opportunity, not a tragedy! Adversity and homelessness were only experiences and knowledge that would lead to an autotelic, bubbly personality with a strong desire to give back.
Many times in her young life, Marguerite relied on the bravery of first responders to provide safety and assistance. As the owner of Salon Margo, she has carried out a vision far surpassing the expectations of a hair salon by encouraging first responders to have a place they can count on, and offer a space that affirms their bravery, courage, and civic duty. The actions of one have the power to change the world, and as such, Marguerite’s vision for her business is to be more, do more and change more than just hair.
Marguerite has uplifted child welfare non-profits, raised money for charity on a multitude of issues through the apparatus of her business, and has advocated at the state capital for child welfare reform. Additionally, she has taken her ardor and experiences, and brought them into a space of positivity, encouragement, and community in hopes to establish a youth program utilizing first responders while forming cohesion and solidarity amongst the community. 
The salon offers a range of hair services from cuts, colors and conditioning treatments, to diy soaps, bathbombs and other personal care products.

**Comment by salonmargo** [comment]
I’m going to have you take out a small section about the first responders. I don’t want to push that anymore .. I’ll get back to you shortly:)

**Comment by jelizarovas** [comment]
Ok

**Comment by jelizarovas** [comment]
Mission
Our purpose is to provide a relaxed atmosphere where guests receive personalized hair services with the intent of elevating self-confidence while sparking the notion of daring you to believe in yourself... One head at a time.
 
Marguerite Swan is an entrepreneur and community activist who custom built her own creative space working diligently and with intent. She sees every appointment as an opportunity to facilitate the betterment of the youth in her community while celebrating those who work as caregivers by helping them love what they see in the mirror. She's designed a space that is more than a salon offering a range of hair services from cuts, colors, and conditioning treatments to diy soaps, bath bombs, and other personal care products.
 
About the Owner
One of six children raised in a broken foster care system from the ages two to twenty three. While some might think this was an obstacle, the passionate and ambitious Ms. Swan would like to impart:
Foster care is an opportunity, not a tragedy! Adversity and homelessness were only experiences and knowledge that would lead to an autotelic, vibrant personality with a strong desire to give back.
 
The actions of one have the power to change the world, and as such, Marguerite’s vision for her business is to be more, do more, and change more than just hair.
She has uplifted child welfare nonprofits, raised money for charity on a multitude of issues through the apparatus of her business, and has advocated at the state capital for child welfare reform. Additionally, she has taken her ardor and experiences, bringing them into a space of positivity, encouragement, and community in hopes to establish a youth program utilizing first responders to form cohesion and amongst the community.
 
Achievements-
Swan, owner and licensed cosmetologist for over 10 years, opened Salon Margo in October 2017. The journey began in 8th grade gaining first-hand experience building a children’s salon designing bath and body products which lead to being product manager and hair stylist at 14 years old.  After high school, she graduated from Paul Mitchell the School of Cosmetology and went on to obtain a degree in Business Administration. At 20 years old, she was certified in keratin education, selling custom keratin to other hair salons. In 2015, earned a credit on IMDB for key hairstylist and most recently, Salon Margo was nominated as “Hartford’s Finest 2019” for raising $1,585 for the Cystic Fibrosis Foundation.
 
What you didn’t know about Salon Margo…
Born on November 11th, Margo has always been aesthetically inclined with an autotelic personality exploring boundaries to express her unique view of the world using creativity as a resilience factor to process undigested material. Want a peek through her lens of the world? The entire design of the shop is a reflection of her character and personality to visually portray a deeper meaning of why she continues to choose hair with the undying passion for giving back.
 
The black and white portray the dark, difficult or vivacious and more memorable moments we experience, while the textured wood symbolizes life and growth becoming stronger as time passes. The silver simply mirrors aspiration in finding the best in every situation as her intent is to show her guests that no matter the obstacle, they are truly one of a kind and her passion is to be a part of your brighter moments.
 
Special thank you from Margo to those who have supported her journey since day 1:
“I don’t feel I express enough the love I have for my hair fam, who have inspired my growth and drive for over a decade. You must know I admire your loyalty and unconditional support of my messy, ambivert brain, for you are the very reason for my success.
I value each friendship and the lessons of taking risks which have strengthened my passion for the craft that has brought me such happiness.
Thank you for choosing me to tame your hairs when you could spend time with any other artist...Thank you for allowing me to be unapologetically ME!”
 
The scheduling book is flexible so just ask:) Hours of service range from 5am -9pm (last appointment). Sundays and Mondays must be booked the Friday before by 6pm the latest. Listed prices begin at shoulder length and are subject to extra costs for detangling, extended growth, additional length, and density due to product/time.
 
If your child has special needs and would like a service, do not hesitate to request. Margo is more than happy to block off however much time it takes to get the job done. First responder flags can be requested through Instagram, Facebook, or simply contacting Margo!

**Comment by jelizarovas** [comment]
From what i can see, you want to change the layout. Right now we have

Welcome
Services
Gallery
About
Reviews
Employment

any of them you want removed? or just add to the page -y?

**Comment by salonmargo** [comment]
- [ ] Change Main photo where you're smiling - change to what?
- [x] Services should all have plus,  remove first responders, 
- [ ] Change gallery - 6 photos
- [ ] Simplify about salon margo
- [ ] New Testimonials + pictures
- [x] Remove dates of reviews
- [ ] Update front of the salon photo
- [x]  Add footnote - hours are flexible os just ask
- [ ]

**Comment by jelizarovas** [comment]
Mission
Our purpose is to elevate self-confidence daring you to believe in yourself... One appointment at a time.
 
 
Her Roots 
Marguerite custom built her own creative space working diligently and with intent. She's designed a space that offers hair services from cuts, colors, and conditioning treatments to DIY soaps, bath bombs, and other personal care products.

The actions of one have the power to change the world, and as such, Marguerite’s vision for her business is to be more, do more, and change more than just hair. Raised in a broken foster care system, most would see this as an obstacle, but her roots prove foster care is an opportunity, not a tragedy! She has uplifted child welfare nonprofits, raised money for charity on a multitude of issues through the apparatus of her business, and has advocated at the state capital for child welfare reform.
 
Marguerite, licensed cosmetologist for over 10 years, began her journey at 14 years old gaining first-hand experience building and managing a children’s spa. As a product designer and hairstylist, she truly enjoyed working with children. From hair wraps, manicures, pedicures, and haircuts; she moved on to graduate Paul Mitchell The School  & Tunxis Community College with a degree in Business Administration. By age 20, she was certified in keratin & selling custom keratin education to hair salons including Paul Mitchell the School. In 2015 she earned a credit on IMDB as Key Hairstylist leading her to open her own salon in late 2017.  In 2019, Salon Margo was nominated as “Hartford’s Finest” to raise money for the Cystic Fibrosis Foundation. 
 
 
The Design
Aesthetically inclined exploring boundaries to express a glimpse through Margo’s lens of the world using creativity as a resilience factor to process undigested material. The shop design portrays a deeper meaning of why she continues to choose hair.
The black and white portray the dark, difficult, or vivacious and more memorable moments we experience, while the textured wood symbolizes life and resilience becoming stronger as time passes. The silver simply mirrors aspiration in finding the best in every situation as her intent is to show her guests that no matter the obstacle, they are truly one of a kind, and her passion is to be a part of your brighter moments.
 
 
 
The scheduling book is flexible so just ask :) Listed prices begin at shoulder length and are subject to extra costs for detangling, extended growth, additional length, and density due to product/time. We service all ages!

**Comment by jelizarovas** [comment]
![image](https://user-images.githubusercontent.com/15138718/149677164-de4170b4-c09d-4181-8f21-8cafe25f7ac4.png)

![image](https://user-images.githubusercontent.com/15138718/149677176-e5202eae-0bc4-44af-8249-fbe48d1f249d.png)

**Comment by jelizarovas** [comment]
- [ ]  from header remove Swan, and remove up and coming - remove that paragraph.
- [ ]  replace it w/ misison
- [ ]  redesign top - will email design concepts
- [ ]  change price woments haircut 35, 
- [ ] root 45,all over color 70, full highlight 125, delete color camo for men, keratin smoothing treatemnt -change to consult,  replace addl charge for length to disclaimer !WILL EMAIL
- [ ] gallery replace with these images (in email) 
![image](https://user-images.githubusercontent.com/15138718/149677485-7d907427-0315-435d-9229-f6c7944e72c0.png)
- [ ] remove about margo - will be replaced !!WILL EMAIL
- [ ] remove testimonialsd
- [ ] work opportunities / put logo there remove picture,  replace with background 
![image](https://user-images.githubusercontent.com/15138718/149677604-fd18dce0-36ef-4d17-8f43-f7604e61d9a4.png)
- [ ] addd Riverbend plaza to adderess top.

**Comment by salonmargo** [comment]
Don't use unicorn logo in gallery, just pictures of the salon. Use unicorn logo at the top of the page where "welcome" section is. Take out "welcome to" but leave the scissors and Salon Margo part
Delete entire "about Salon Margo" tab
All photos that include Margo's face should be taken out. the only photos on the website will be in the "gallery" besides that background one

**Comment by jelizarovas** [comment]
was asked to take the website down.
