### ISSUE TITLE
change services font to comic sans

### ISSUE THREAD

**Issue by salonmargo** [jelizarovas/HairByMargo.Com#5]
![image](https://user-images.githubusercontent.com/60369612/73224132-85f9c700-4136-11ea-9ce9-653ecd642050.png)

change it here

![image](https://user-images.githubusercontent.com/60369612/73224193-b2adde80-4136-11ea-8206-6fa1ea4083f7.png)

**Comment by jelizarovas** [comment]
reopen issue if needed with font names and which you would like replaced
